version: '3'
services:
  mysql:
    image: mariadb
    volumes:
      - /data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: db_wordp
      MYSQL_USER: user_wordp
      MYSQL_PASSWORD: pass
    ports:
      - 172.17.0.1:3306:3306
    restart: always

  wordpress:
    image: wordpress:php7.3-fpm-alpine
    volumes:
      - /data/html:/var/www/html
      - ./www.conf:/usr/local/etc/php-fpm.d/www.conf
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      MYSQL_ROOT_PASSWORD: pass
      WORDPRESS_DB_NAME: db_wordp
      WORDPRESS_DB_USER: user_wordp
      WORDPRESS_DB_PASSWORD: pass
      WORDPRESS_TABLE_PREFIX: wp_
    links:
      - mysql
    ports:
     - 172.17.0.1:9000:9000
    restart: always

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_wp.conf:/etc/nginx/conf.d/nginx_wp.conf
      - /data/html:/var/www/html
    ports:
      - 172.17.0.1:8080:80
      - 172.17.0.1:9146:9146
      - 172.17.0.1:9145:9145
    links:
      - wordpress
