global:
 scrape_interval: 10s
scrape_configs:
  - job_name: 'prometheus_master'
    scrape_interval: 5s
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'nginx'
    scrape_interval: 5s
    static_configs:
    - targets: ['172.17.0.1:9113']
  - job_name: 'php-fpm'
    scrape_interval: 5s
    static_configs:
    - targets: ['172.17.0.1:9253']
  - job_name: 'mariadb'
    scrape_interval: 5s
    static_configs:
    - targets: ['172.17.0.1:9104']
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://65.108.93.46:9090
        - http://172.17.0.1:8080
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 172.17.0.1:9115
  - job_name: 'blackbox_exporter'
    static_configs:
      - targets: ['172.17.0.1:9115']
